<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AnalysisMode>Recommended</AnalysisMode>
        <Authors>Thomas C. Flanagan</Authors>
        <Company>TcfOss</Company>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/tcfoss/string-enum-generator</PackageProjectUrl>
        <RepositoryUrl>https://github.com/tcfoss/string-enum-generator</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    </PropertyGroup>

    <PropertyGroup>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <MinVerTagPrefix>v</MinVerTagPrefix>
    </PropertyGroup>

    <Target Name="OverrideVersions" AfterTargets="MinVer">
        <PropertyGroup>
            <!-- Update only when major version changes -->
            <AssemblyVersion>1.0.0.0</AssemblyVersion>
        </PropertyGroup>
    </Target>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="/" />
    </ItemGroup>
</Project>
